/** @type {import('tailwindcss').Config} */
module.exports = {
  important: true,
  content: [ "./app/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "group/h1",
    "group/h2",
    "group/h3",
    "group/text",
    "group/paragraph",
    "group/image",
    "group/button",
    "group/html",
    "group/divider",
    "group/container",
    "group/grid",
    "group/flex-row",
    "group/flex-column",
    "group/quote",
    "group/code",
    "group/video",
    "group-hover/h1:opacity-100",
    "group-hover/h2:opacity-100",
    "group-hover/h3:opacity-100",
    "group-hover/text:opacity-100",
    "group-hover/paragraph:opacity-100",
    "group-hover/image:opacity-100",
    "group-hover/button:opacity-100",
    "group-hover/html:opacity-100",
    "group-hover/divider:opacity-100",
    "group-hover/container:opacity-100",
    "group-hover/grid:opacity-100",
    "group-hover/flex-row:opacity" - 100,
    "group-hover/flex-column:opacity" - 100,
    "group-hover/quote:opacity-100",
    "group-hover/code:opacity-100",
    "group-hover/video:opacity-100",
  ],
  theme: {
    extend: {
      fontFamily: {
        dmSerifDisplay: ["var(--font-dmSerif)"],
        poppins: ["var(--font-poppins)"],
      },
      colors: {
        primary: "var(--primary)",
        background: "var(--background)",
        "primary-100": "var(--primary-100)",
        "primary-900": "var(--primary-900)",
        "primary-foreground": "var(--primary-foreground)",
        "primary-transparent": "var(--primary-transparent)",
        "light-primary": "var(--light-primary)",
        "light-primary-transparent": "var(--light-primary-transparent)",
        main: "var(--text-main)",
        secondary: "var(--text-secondary)",
      },
      scale: {
        102: "1.02",
      },
      boxShadow: {
        soft: "0 0 15px 0 rgba(0,0,0,0.05)",
      },
      borderRadius: {
        base: "10px",
      },
      keyframes: {
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-5px)" },
          "50%": { transform: "translateX(5px)" },
          "75%": { transform: "translateX(-5px)" },
        },
      },
      animation: {
        shake: "shake 0.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
