import { JobData } from "@/types";
import { SalaryCurrency } from "../enums/currency.enum";

export const INITIAL_JOB_DATA: JobData = {
  companyId: null,
  title: "",
  jobIndustryId: null,
  jobIndustryName: null,
  jobSpecialityId: null,
  jobSpecialityName: null,
  jobCategoryId: null,
  jobCategoryName: null,
  jobCareerLevelId: null,
  jobCareerLevelName: null,
  jobEmploymentTypeId: null,
  jobEmploymentTypeName: null,
  jobWorkPlace: null,
  gender: null,
  minAge: null,
  maxAge: null,
  educationLevel: null,
  country: null,
  city: null,
  maxExpYears: null,
  minExpYears: null,
  hideSalary: true,
  salaryRangeStart: null,
  salaryRangeEnd: null,
  salaryCurrency: SalaryCurrency.USD,
  availableVacancies: 1,
  description: null,
  requirements: null,
  salaryDetails: null,
  keywords: [],
  skills: [],
  questions: [],
  showCompany: true,
  recieveEmails: true,
  jobEmail: null,
  draft: false,
  active: true,
  closed: false,
  startDateType: null,
  validTo: null,
};
