export const dummyCandidates: CandidateType[] = [
  {
    id: "cand001",
    avatar: "https://example.com/avatars/john_doe.jpg",
    userName: "john_doe",
    firstName: "John",
    lastName: "Doe",
    applyDate: "2025-02-15",
    title: "Senior Software Engineer",
    whatsApp: "+1-555-123-4567",
    phone: "+1-555-123-4567",
    email: "john.doe@example.com",
    country: { code: "US", name: "United States" },
    state: { code: "CA", name: "California" },
    city: "San Francisco",
    yearsOfExperience: 8,
    category: "Technology",
    specialty: "Full-Stack Development",
    careerLevel: "Senior",
    isShortlisted: true,
    isUnlocked: true,
    isAvailable: true,
    lastExperience: {
      id: "exp001",
      name: "TechCorp",
      title: "Software Engineer",
      country: { code: "US", name: "United States" },
      state: { code: "CA", name: "California" },
      city: "San Francisco",
      startDate: "2020-03-01",
      endDate: "2024-12-31",
      isPresent: false,
    },
    lastEducation: {
      id: "edu001",
      inistitute: "Stanford University",
      degree: "Master of Science in Computer Science",
      country: { code: "US", name: "United States" },
      startYear: 2014,
      endYear: 2016,
      grade: "3.9 GPA",
    },
    folders: ["tech_candidates", "shortlisted"],
  },
  {
    id: "cand002",
    avatar: "https://example.com/avatars/jane_smith.jpg",
    userName: "jane_smith",
    firstName: "Jane",
    lastName: "Smith",
    applyDate: "2025-03-01",
    title: "Marketing Manager",
    whatsApp: "+44-7700-900123",
    phone: "+44-7700-900123",
    email: "jane.smith@example.com",
    country: { code: "UK", name: "United Kingdom" },
    state: { code: "ENG", name: "England" },
    city: "London",
    yearsOfExperience: 5,
    category: "Marketing",
    specialty: "Digital Marketing",
    careerLevel: "Mid-Level",
    isShortlisted: false,
    isUnlocked: true,
    isAvailable: false,
    lastExperience: {
      id: "exp002",
      name: "MarketPeak",
      title: "Marketing Specialist",
      country: { code: "UK", name: "United Kingdom" },
      state: { code: "ENG", name: "England" },
      city: "London",
      startDate: "2022-06-01",
      endDate: "",
      isPresent: true,
    },
    lastEducation: {
      id: "edu002",
      inistitute: "University of Oxford",
      degree: "Bachelor of Arts in Business",
      country: { code: "UK", name: "United Kingdom" },
      startYear: 2016,
      endYear: 2019,
      grade: "First Class",
    },
    folders: ["marketing_candidates"],
  },
  {
    id: "cand003",
    avatar: "https://example.com/avatars/ali_khan.jpg",
    userName: "ali_khan",
    firstName: "Ali",
    lastName: "Khan",
    applyDate: "2025-01-20",
    title: "Junior Graphic Designer",
    whatsApp: "+91-98765-43210",
    phone: "+91-98765-43210",
    email: "ali.khan@example.com",
    country: { code: "IN", name: "India" },
    state: { code: "MH", name: "Maharashtra" },
    city: "Mumbai",
    yearsOfExperience: 2,
    category: "Design",
    specialty: "Graphic Design",
    careerLevel: "Entry-Level",
    isShortlisted: false,
    isUnlocked: false,
    isAvailable: true,
    lastExperience: null,
    lastEducation: {
      id: "edu003",
      inistitute: "Mumbai University",
      degree: "Bachelor of Fine Arts",
      country: { code: "IN", name: "India" },
      startYear: 2019,
      endYear: 2022,
      grade: "85%",
    },
    folders: ["design_candidates", "new_applicants"],
  },
];