import { RoleBasedLinks } from "@/types";
import {
  BusinessOutlined,
  DescriptionOutlined,
  FolderOutlined,
  HelpOutline,
  HomeOutlined,
  MessageOutlined,
  NotificationsActiveOutlined,
  PaidOutlined,
  PostAddOutlined,
  Search,
  SettingsOutlined,
  WorkOutline,
} from "@mui/icons-material";
import { GraduationCap, UserCog, Users, Users2 } from "lucide-react";

export const roleBasedSideBarLinks: RoleBasedLinks = {
  admin: [
    {
      id: 0,
      type: "profile",
      pattern: "/me/[id]",
    },
    {
      id: 1,
      label: "Dashboard",
      icon: HomeOutlined,
      path: "/admin",
    },
    {
      id: 2,
      label: "Manage All Users",
      icon: Users,
      type: "collapse",
      links: [
        {
          id: 1,
          label: "Manage Employers",
          icon: WorkOutline,
          path: "/admin/employers",
          type: "supLink",
        },
        {
          id: 2,
          label: "Manage Job Seekers",
          icon: GraduationCap,
          path: "/admin/seekers",
          type: "supLink",
        },
        {
          id: 3,
          label: "Medicova Team",
          icon: UserCog,
          path: "/admin/employees",
          type: "supLink",
        },
      ],
    },
    {
      id: 6,
      label: "Content",
      icon: WorkOutline,
      type: "collapse",
      links: [
        {
          id: 61,
          label: "Home Page",
          icon: WorkOutline,
          path: "#",
          type: "supLink",
        },
        {
          id: 62,
          label: "Search Page",
          icon: WorkOutline,
          path: "#",
          type: "supLink",
        },
        {
          id: 63,
          label: "Company Page",
          icon: PostAddOutlined,
          path: "#",
          type: "supLink",
        },
        {
          id: 64,
          label: "Seeker Page",
          icon: PostAddOutlined,
          path: "#",
          type: "supLink",
        },
      ],
    },
    {
      id: 7,
      label: "Manage Jobs",
      icon: HomeOutlined,
      path: "/admin/jobs",
    },
    {
      id: 8,
      label: "Manage Applications",
      icon: HomeOutlined,
      path: "#",
    },
    {
      id: 11,
      label: "Billing & Subscription",
      icon: PaidOutlined,
      path: "/admin/plans",
    },
    {
      id: 12,
      label: "Report",
      icon: DescriptionOutlined,
    },
    {
      id: 13,
      label: "Chat",
      icon: MessageOutlined,
      path: "/chat",
      notifications: 3,
    },
    {
      id: 40,
      icon: NotificationsActiveOutlined,
      label: "Notifications",
      path: "/notifications",
      notifications: 4,
    },
    {
      id: 15,
      type: "text",
      section: "Settings",
    },
    {
      id: 16,
      label: "Settings",
      icon: SettingsOutlined,
      path: "#",
    },
    {
      id: 17,
      label: "Help Center",
      icon: HelpOutline,
    },
  ],
  default: [],
  employer: [
    {
      id: 0,
      type: "profile",
      pattern: "/co/[id]",
    },
    {
      id: 1,
      label: "Dashboard",
      icon: HomeOutlined,
      path: "/employer/dashboard",
    },
    {
      id: 2,
      label: "Company Info",
      icon: BusinessOutlined,
      path: "/employer/company-info",
    },
    {
      id: 3,
      label: "Jobs",
      icon: WorkOutline,
      type: "collapse",
      links: [
        {
          id: 4,
          label: "Manage Jobs",
          icon: WorkOutline,
          path: "/employer/job/manage-jobs",
          pattern: "/employer/job/manage-jobs/*",
          type: "supLink",
        },
        {
          id: 5,
          label: "Post New Job",
          icon: PostAddOutlined,
          path: "/employer/job/posted",
          pattern: "/employer/job/posted/*",
          type: "supLink",
        },
      ],
    },
    {
      id: 7,
      label: "Search",
      icon: Search,
      type: "collapse",
      links: [
        {
          id: 8,
          label: "Search",
          icon: Search,
          path: "/employer/search",
          type: "supLink",
        },
        {
          id: 10,
          label: "My Folders",
          icon: FolderOutlined,
          path: "/employer/search/saved-search",
          pattern: "/employer/search/saved-search/*",
          type: "supLink",
        },
      ],
    },
    {
      id: 11,
      label: "Billing & Subscription",
      icon: PaidOutlined,
      path: "/employer/subscription-plans",
    },
    {
      id: 12,
      label: "Report",
      icon: DescriptionOutlined,
    },
    {
      id: 13,
      label: "Chat",
      icon: MessageOutlined,
      path: "/chat",
      notifications: 3,
    },
    {
      id: 40,
      icon: NotificationsActiveOutlined,
      label: "Notifications",
      path: "/notifications",
      notifications: 4,
    },
    {
      id: 15,
      type: "text",
      section: "Settings",
    },
    {
      id: 16,
      label: "Settings",
      icon: SettingsOutlined,
      path: "/employer/setting",
    },
    {
      id: 17,
      label: "Help Center",
      icon: HelpOutline,
    },
  ],
  unEmployee: [
    {
      id: 2,
      label: "Company Info",
      icon: BusinessOutlined,
      path: "/employer/company-info",
    },
  ],
  seeker: [
    {
      id: 0,
      type: "profile",
      pattern: "/me/[id]",
    },
    // {
    //   id: 18,
    //   icon: HomeOutlined,
    //   label: "Home",
    //   path: "/",
    // },
    {
      id: 20,
      icon: MessageOutlined,
      label: "Messages",
      path: "/chat",
      notifications: 3,
    },
    {
      id: 21,
      icon: DescriptionOutlined,
      label: "My Applications",
      path: "/job-seeker/my-applications",
    },
    {
      id: 22,
      icon: Search,
      label: "Find Jobs",
      path: "/a/explore",
      pattern: "/a/*",
    },
    {
      id: 23,
      icon: BusinessOutlined,
      label: "Browse Companies",
      path: "/job-seeker/browse-companies",
    },
    {
      id: 24,
      icon: NotificationsActiveOutlined,
      label: "Notifications",
      path: "/notifications",
      notifications: 4,
    },

    {
      id: 26,
      section: "Settings",
      type: "text",
    },
    {
      id: 27,
      icon: SettingsOutlined,
      label: "Settings",
      path: "/job-seeker/setting",
      pattern: "/job-seeker/setting/*",
    },
    {
      id: 28,
      icon: HelpOutline,
      label: "Help Center",
      path: "#",
    },
  ],
};

export const applicantsFilters = {
  Residency: [
    { label: "All", count: 100, value: "all" },
    { label: "Egypt", count: 50, value: "egypt" },
    { label: "Qatar", count: 50, value: "qatar" },
  ],
  nationality: [
    { label: "All", count: 200, value: "all" },
    { label: "Egyptian", count: 120, value: "egyptian" },
    { label: "Saudi Arabian", count: 80, value: "saudi" },
  ],
  industry: [
    { label: "All", count: 300, value: "all" },
    { label: "Physicians", count: 150, value: "physicians" },
    { label: "Dentists", count: 50, value: "dentists" },
    { label: "Physical Therapists", count: 40, value: "physical_therapists" },
    { label: "Pharmacists", count: 30, value: "pharmacists" },
    { label: "Nurses", count: 30, value: "nurses" },
  ],
  category: [
    { label: "All", count: 200, value: "all" },
    { label: "Doctor", count: 100, value: "doctor" },
    { label: "Nurse", count: 50, value: "nurse" },
    { label: "Pharmaceutical", count: 30, value: "pharmaceutical" },
    { label: "Physicalists", count: 10, value: "physicalists" },
    { label: "Specialized", count: 10, value: "specialized" },
  ],
  educationLevel: [
    { label: "All", count: 250, value: "all" },
    { label: "Institute", count: 50, value: "institute" },
    { label: "Bachelor’s Degree", count: 100, value: "bachelor" },
    { label: "Doctorate Degree", count: 70, value: "doctorate" },
    { label: "Fellowship", count: 30, value: "fellowship" },
  ],
  yearsOfExperience: [
    { label: "All", count: 150, value: "all" },
    { label: "1-3", count: 50, value: "1-3" },
    { label: "3-5", count: 40, value: "3-5" },
    { label: "5-10", count: 30, value: "5-10" },
    { label: "+10", count: 30, value: "10+" },
  ],
  gender: [
    { label: "All", count: 300, value: "all" },
    { label: "Male", count: 200, value: "male" },
    { label: "Female", count: 100, value: "female" },
  ],
  age: [
    { label: "18-25", count: 40, value: "18-25" },
    { label: "26-35", count: 50, value: "26-35" },
    { label: "36-45", count: 30, value: "36-45" },
    { label: "46-60", count: 20, value: "46-60" },
    { label: "60+", count: 10, value: "60+" },
  ],
};
