import ThemeProviderClient from "./ThemeProviderClient";
import { DM_Serif_Display, Poppins } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import DynamicHeader from "@/components/Layout/Header/Header";
import DynamicLayout from "@/components/Layout/layout";
import { NextAuthProvider } from "@/NextAuthProvider";
import { Suspense } from "react";
import HeaderSelector from "@/components/Layout/Header/SelectedHeader";
import SideBar from "@/components/Layout/SideBar/SideBar";
import DynamicSideBar from "@/components/Layout/SideBar/dynamic-side-bar";

const dmSerifDisplay = DM_Serif_Display({
  subsets: ["latin"],
  variable: "--font-dmSerif",
  weight: "400",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Medicova",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dmSerifDisplay.variable} ${poppins.variable} font-poppins`}
      >
        <ThemeProviderClient>
          <StoreProvider>
            <NextAuthProvider>
              <Suspense fallback={<HeaderSelector />}>
                <DynamicHeader />
              </Suspense>
              <DynamicLayout>
                <Suspense fallback={<DynamicSideBar />}>
                  <SideBar />
                </Suspense>
                <div className="flex-1">{children}</div>
              </DynamicLayout>
            </NextAuthProvider>
          </StoreProvider>
        </ThemeProviderClient>
      </body>
    </html>
  );
}
